### PR TITLE
Added test coverage

### PR DESCRIPTION
**Pull request by jrit**
@dmaloneycalu a few small fixes for watchers, utils, and working with ngDialog along the way here. No API changes.

### CODE REVIEW

**Comment by jrit** [comment]
Going to try getting this running on Travis before this is merged, not sure why I didn't do that already.

**Comment by dmaloneycalu** [comment]
Any reason for travis over Drone?

**Comment by jrit** [comment]
The project is public but our instance of Drone is private, so I use the public Travis for public repos.

**Comment by dmaloneycalu** [comment]
Once the Travis build is functioning, this LGTM

**Pull request merged**
